SYMBOLS = [
    "BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT",
    "ADAUSDT","DOGEUSDT","AVAXUSDT","TRXUSDT","DOTUSDT",
    "MATICUSDT","LTCUSDT","LINKUSDT","BCHUSDT","ATOMUSDT",
    "ETCUSDT","XLMUSDT","ICPUSDT","FILUSDT","APTUSDT",
    "NEARUSDT","HBARUSDT","QNTUSDT","OPUSDT","INJUSDT",
    "IMXUSDT","GRTUSDT","RNDRUSDT","ARBUSDT","STXUSDT",
    "AAVEUSDT","MKRUSDT","EGLDUSDT","SANDUSDT","THETAUSDT",
    "AXSUSDT","XTZUSDT","NEOUSDT","KAVAUSDT","FLOWUSDT",
    "MINAUSDT","CHZUSDT","CRVUSDT","DYDXUSDT","ZECUSDT",
    "COMPUSDT","ENJUSDT","1INCHUSDT","SNXUSDT"
]
